"""add unique constraint on user_skills user_id skill_name

Revision ID: 67604beb8fae
Revises: b2c3d4e5f6a7
Create Date: 2026-03-26 11:51:31.795667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67604beb8fae'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'difficulty_level',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.drop_constraint(op.f('user_skills_user_id_skill_name_key'), 'user_skills', type_='unique')
    op.create_unique_constraint('uq_user_skill_user_skill_name', 'user_skills', ['user_id', 'skill_name'])
    op.alter_column('users', 'resume_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('users', 'github_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'github_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.alter_column('users', 'resume_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    op.drop_constraint('uq_user_skill_user_skill_name', 'user_skills', type_='unique')
    op.create_unique_constraint(op.f('user_skills_user_id_skill_name_key'), 'user_skills', ['user_id', 'skill_name'])
    op.alter_column('courses', 'difficulty_level',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
