"""baseline schema

Revision ID: 789321a178d7
Revises: 
Create Date: 2026-03-08 09:32:40.072574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789321a178d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'difficulty_level',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('users', 'resume_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('users', 'github_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'github_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.alter_column('users', 'resume_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('courses', 'difficulty_level',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
